### ISSUE TITLE
Caught exception when trying to load file of format [py]: __init__() missing 1 required keyword-only argument: 'executable'

### ISSUE THREAD

**Issue by rjrs23** [Slamtec/sllidar_ros2#2]
Hello

I have tried to follow the instructions on the repo to install this package on ros2 galactic and am encountering the above error when am trying to launch the node. 

```
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2022-02-25-20-53-38-777999-user-desktop-793818
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /home/user/ros2_galactic/build/launch/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/home/user/ros2_galactic/build/launch/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/home/user/ros2_galactic/build/launch/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/user/ros2_galactic/install/sllidar_ros2/share/sllidar_ros2/launch/sllidar_launch.py", line 48, in generate_launch_description
    Node(
TypeError: __init__() missing 1 required keyword-only argument: 'executable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/ros2_galactic/build/launch/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/home/user/ros2_galactic/build/launch/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/home/user/ros2_galactic/build/launch/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/home/user/ros2_galactic/build/launch/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/home/user/ros2_galactic/build/launch/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/home/user/ros2_galactic/build/launch/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/home/user/ros2_galactic/build/launch/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/home/user/ros2_galactic/build/launch/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/home/user/ros2_galactic/build/launch/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/home/user/ros2_galactic/build/launch/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: __init__() missing 1 required keyword-only argument: 'executable'

```

Can someone please look into what the problem is ? I am unable to figure out the issue.

**Comment by Gianstiff** [comment]
Hi!

I suppose the error is related to the content of the launch file.
From galactic distro I think the labels "node_executable" and "node_name" have been deprecated as also reported here #1.
Modifying such labels to "executable" and "name", it should work.

**Comment by hello-chintan** [comment]
Submitted a patch for the issue. Check PR #3

**Comment by vinicentus** [comment]
Would this close #1 and #2?

**Comment by xiaoc10020015** [comment]
+1
